### ISSUE TITLE
Segmentation fault with "large" trajectory

### ISSUE THREAD

**Issue by wrmartin** [BioComputingUP/ring-pymol#5]
When attempting to run the plugin on a 10,000 frame trajectory (300 residue protein), the everything bombs out and throws a segmentation fault after roughly 30 seconds. It appears to be failing when attempting to generate the .cif file. The occurs both when using the webserver and when running locally. A 1000 frame trajectory does load just fine, but it would be nice to be able to use it for much larger trajectories.

**Comment by AlessioDelConte** [comment]
Hi,
exporting the cif file is done using PyMOL, so if it crashes doing that I cannot really help you out. To confirm this can you please try to export your model yourself and see if it still doesn't work?  "File > Export Molecule"  and select all models.

**Comment by AlessioDelConte** [comment]
Yes thats totally doable, with `cmd.count_states(obj_name)`, in PyMOL each model of the trajectory is called state. Taking this number and assigning it to `len_traj` should do the trick, even though I don't really like the fact that it has to write a lot of files to do that, but it seems that it is the only option here.
Can you be so kind to open pull request with this fix so I can merge it into the codebase? Otherwise I will do it myself, no problem.
Thanks again!

**Comment by wrmartin** [comment]
I've not done that before, so hopefully I did it correctly. I also didn't like writing all of those files, but it does clean up after itself at least.
